sudo: required
language: generic

services:
  - docker

before_install:
  - npm install --save enzyme enzyme-adapter-react-16 react-test-renderer
  - docker build -t xtianexica/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xtianexica/react-test npm test

after_success:
  - docker build -t xtianexica/multi-client ./client
  - docker build -t xtianexica/multi-nginx ./nginx
  - docker build -t xtianexica/multi-server ./server
  - docker build -t xtianexica/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push xtianexica/multi-client
  - docker push xtianexica/multi-nginx
  - docker push xtianexica/multi-server
  - docker push xtianexica/multi-worker


